        .text
        .global mova_encodings
mova_encodings:
        .inst 0xc0c28400
        .inst 0xc0c08400
        .inst 0xc0c68400
        .inst 0xc0ca8400
        .inst 0xc0d28400
        .inst 0xc0c24400
        .inst 0xc0c2c400
        .inst 0xc0c20400
        .inst 0xc0c20402
        .inst 0xc0c20404
        .inst 0xc0c20406
        .inst 0xc0c20480
        .inst 0xc0c20500
        .inst 0xc0c20580
        .inst 0xc0c20980
        .inst 0xc0c20440
        .inst 0xc0c204c0
        .inst 0xc0c20540
        .inst 0xc0c205c0
        ret
